name: Convert GPT-Neo 125M to ONNX

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch --upgrade
          pip install onnx onnxruntime transformers --upgrade

      - name: Run conversion script
        run: python scripts/convert_gptneo_onnx.py

      - name: Upload ONNX artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpt-neo-125-onnx
          path: ./model_onnx/gpt_neo_125.onnx
