name: Convert GPT-Neo 125M to TFLite

on:
  workflow_dispatch:  # esegui manualmente

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers tensorflow

      - name: Run conversion script
        run: python scripts/convert_gptneo.py

      - name: Upload TFLite artifact
        uses: actions/upload-artifact@v3
        with:
          name: gpt-neo-125-tflite
          path: ./model_tf/gpt_neo_125.tflite
