name: Predict and Rank Stocks

on:
  workflow_dispatch:  # Permette di avviare il workflow manualmente
  
jobs:
  run-predict-stock-growth:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Scarica i file dal repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specifica la versione di Python che serve, ad esempio 3.9 o 3.10
      # Installa le dipendenze necessarie
      - name: Install dependencies
        run: |
          pip install requests
          pip install os
          pip install beautifulsoup4
          pip install scikit-learn
          pip install numpy
          
      - name: Run predict_stock_growth.py script
        run: |
          python scripts/predict_stock_growth.py
