name: Predict and Rank Stocks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 17 * * *'  # Esecuzione giornaliera alle 12:00 UTC
  workflow_dispatch:  # Aggiungi il trigger manuale


jobs:
  data_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas scikit-learn beautifulsoup4

      - name: Run finance analysis
        run: python scripts/predict_stock_growth.py  # Assicurati di inserire "scripts/" prima del nome del file
