name: Predict and Rank Stocks

on:
  workflow_dispatch:  # Permette di avviare il workflow manualmente
  
jobs:
  run-predict-stock-growth:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Scarica i file dal repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specifica la versione di Python che serve, ad esempio 3.9 o 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installa le dipendenze da un eventuale file requirements.txt

      - name: Run predict_stock_growth.py script
        run: |
          python scripts/predict_stock_growth.py
