name: Predict and Rank Stocks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 17 * * *'  # Esecuzione giornaliera alle 12:00 UTC
  workflow_dispatch:  # Trigger manuale

jobs:
  data_analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup di Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Installazione delle dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas scikit-learn beautifulsoup4

      # Step 4: Esecuzione dello script Python di analisi finanziaria
      - name: Run finance analysis
        run: python scripts/predict_stock_growth.py  # Modifica se il tuo file è in una cartella diversa

      # Step 5: Archiviazione dei risultati o altre azioni
      - name: Archive results
        run: |
          mkdir -p results
          mv predictions.csv results/  # Salva i risultati in un file .csv, modificando il codice Python per esportare i risultati se necessario.
