name: Predict and Rank Stocks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0,16,20 * * *'  # Esecuzione giornaliera alle 12:00 UTC

jobs:
  predict_and_rank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 scikit-learn pandas

      - name: Run prediction script
        run: python scripts/predict_stock_growth.py  # Assicurati di inserire "scripts/" prima del nome del file

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3  # Usa la nuova versione `v3`
        with:
          name: results
          path: results/
