name: Predict and Rank Stocks

on:
  schedule:
    - cron: '13 19 * * *'  # Esegue alle 19:13 UTC ogni giorno
  workflow_dispatch:  # Permette di eseguire il workflow manualmente

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 scikit-learn PyGithub

    - name: Run prediction script
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}   # Assicurati di aver aggiunto la chiave API nei segreti del repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token GitHub con permessi di scrittura sul repository
      run: python scripts/predict_stock_growth.py
