name: Predict and Rank Stocks
# Permetti l'esecuzione manuale tramite GitHub Actions
on:
  workflow_dispatch:  # Evento che consente l'esecuzione manuale

jobs:
  process_data:
    runs-on: ubuntu-latest  # Esegui su un runner Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout del codice sorgente del repository

      - name: Set up Python environment
        uses: actions/setup-python@v2  # Imposta Python
        with:
          python-version: '3.x'  # Sostituisci con la versione desiderata di Python

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas  # Installa le dipendenze necessarie

      - name: Run Python script
        run: python scripts/predict_stock_growth.py  # Esegui lo script Python (modifica il nome se necessario)
