name: Predict and Rank Stocks

on:
  schedule:
    - cron: '18 */24 * * *'  # Esecuzione ogni 4 ore, all'inizio dell'ora (00:00, 04:00, 08:00, ecc.)
  workflow_dispatch:  # Per avviare manualmente se necessario

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 scikit-learn xgboost PyGithub  # Aggiungi PyGithub

    - name: Run prediction script
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}   # Assicurati di aver aggiunto la chiave API nei segreti del repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token GitHub con permessi di scrittura sul repository
      run: python scripts/predict_stock.py
