name: Predict and Rank Stocks

# Definisce quando eseguire il workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0,16,20 * * *'  # Esecuzione giornaliera alle 12:00 UTC

jobs:
  predict_and_rank:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Imposta Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Installa le dipendenze necessarie
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 scikit-learn pandas

      # Esegue lo script Python per le previsioni e la classifica
      - name: Run prediction script
        run: python predict_stock_growth.py  # Sostituisci con il nome del tuo script

      # Salva i risultati (output) come artefatti, se desiderato
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/
